version: "2"

run:
  timeout: 1m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - errchkjson
    - ineffassign
    - unused
    - goconst
    - gocyclo
    - govet
    - gocognit
    - lll
    - misspell
    - mnd

  settings:
    lll:
      line-length: 120
      tab-width: 1
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 10
    gocognit:
      min-complexity: 10
