services:
  postgres:
    image: postgres:17
    env_file: .env.example
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 30

  redis:
    image: redis:7.4
    env_file: .env.example
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 30

  rabbitmq:
    image: rabbitmq:3.12-management
    env_file: .env.example
    restart: always
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 1s
      timeout: 1s
      retries: 30